### ISSUE TITLE
Erro no tracking codes, não atualizando status do pedido

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-frenet#10]
Estou acompanhando aqui duas lojas que vendem via frenet e os status dos pedidos não são atualizados. Mas a que reclamou apenas é 1077. Fiz um teste de um pedido por exemplo 5fa699c4b2161709fa493588 que tem o corpo abaixo e na resposta, mostrava que foi entregue, mas no pedido não houve atualização. Nem enviado ou entregue

{
   "ShippingServiceCode":"04669",
   "TrackingNumber":"OL383921541BR",
   "InvoiceNumber":"",
   "InvoiceSerie":"",
   "RecipientDocument":"",
   "OrderNumber":""
}

**Comment by matheusgnreis** [comment]
@leomp12

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-frenet/commit/71fa482ad7d6014c66f01a6a4057b96582e1b01f

**Comment by leomp12** [comment]
@matheusgnreis lembrando que, como houve alteração nos procedures [aqui](https://github.com/ecomplus/app-frenet/commit/71fa482ad7d6014c66f01a6a4057b96582e1b01f#diff-c3b8c3dbd7e608bfda51c020c2779f5129482cbab302151457359d8bddb0a6c5), é necessário reinstalar o aplicativo para fixar o problema (ou remover o procedure anterior e adicionar o novo via API).

**Comment by matheusgnreis** [comment]
Ok

**Comment by matheusgnreis** [comment]
Boa noite, segue com problema para atualizar os status

**Comment by matheusgnreis** [comment]
5fb04a9580c6216a3fc5f685
Em 21/11/2020 09:40
Objeto entregue ao destinatário	Local
CDD TAGUATINGA NORTE
BRASILIA / DF

**Comment by matheusgnreis** [comment]
Mesma loja

**Comment by leomp12** [comment]
Deve estar relacionado a isso também https://github.com/ecomplus/app-frenet/issues/11 , talvez tenha uma fila travada nessa de tentar infinitamente os códigos inválidos, talvez não passou da loja 1011...

**Comment by talissonf** [comment]
Arrumado! era um problema com o sqlite, eu tentava salvar o status antes de atualizar o pedido. Como ele não salvava o status o pedido não era atualizado.

https://github.com/ecomplus/app-frenet/compare/6c5bc19fdf...f8bd59b10e
