### ISSUE TITLE
Valor errado mostrando no frete

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-frenet#14]
É a requisição que vem no network
[
  {
    "label": "PAC",
    "carrier": "Correios",
    "service_name": "PAC",
    "service_code": "FR04596",
    "shipping_line": {
      "from": {
        "zip": "74932230",
        "street": "Rua 7 E",
        "complement": "Qd43 Lt 27 casa 2",
        "province_code": "GO",
        "borough": "GARAVELO R PARK",
        "city": "APARECIDA DE GOIANIA",
        "province": "GOIÁS",
        "country": "BRASIL",
        "number": 0
      },
      "to": {
        "zip": "30140072"
      },
      "delivery_time": {
        "days": 10,
        "working_days": true
      },
      "price": 23.47,
      "total_price": 23.47,
      "custom_fields": [
        {
          "field": "by_frenet",
          "value": "true"
        },
        {
          "field": "frenet:took",
          "value": "257"
        }
      ],
      "own_hand": false,
      "receipt": false
    }
  },
  {
    "label": "Sedex",
    "carrier": "Correios",
    "service_name": "Sedex",
    "service_code": "FR04014",
    "shipping_line": {
      "from": {
        "zip": "74932230",
        "street": "Rua 7 E",
        "complement": "Qd43 Lt 27 casa 2",
        "province_code": "GO",
        "borough": "GARAVELO R PARK",
        "city": "APARECIDA DE GOIANIA",
        "province": "GOIÁS",
        "country": "BRASIL",
        "number": 0
      },
      "to": {
        "zip": "30140072"
      },
      "delivery_time": {
        "days": 3,
        "working_days": true
      },
      "price": 52.66,
      "total_price": 52.66,
      "custom_fields": [
        {
          "field": "by_frenet",
          "value": "true"
        },
        {
          "field": "frenet:took",
          "value": "257"
        }
      ],
      "own_hand": false,
      "receipt": false
    }
  }
]
A que está vindo da frenet
{
  "ShippingSevicesArray": [
    {
      "ServiceCode": "04596",
      "ServiceDescription": "PAC",
      "Carrier": "Correios",
      "CarrierCode": "COR",
      "ShippingPrice": "9.90",
      "DeliveryTime": "10",
      "Msg": "",
      "Error": false,
      "OriginalDeliveryTime": "9",
      "OriginalShippingPrice": "23.57",
      "ResponseTime": "147.8124",
      "AllowBuyLabel": false
    },
    {
      "ServiceCode": "04014",
      "ServiceDescription": "Sedex",
      "Carrier": "Correios",
      "CarrierCode": "COR",
      "ShippingPrice": "52.86",
      "DeliveryTime": "3",
      "Msg": "",
      "Error": false,
      "OriginalDeliveryTime": "2",
      "OriginalShippingPrice": "52.86",
      "ResponseTime": "384.4944",
      "AllowBuyLabel": false
    }
Não está aparecendo o preço do desconto, fiz esse teste mais de uma vez pra ver se tinha erro ou não. Na API sempre tinha o preço de 9.9 que é desconto.

**Comment by leomp12** [comment]
Uai acho que esse teste aí não tá muito certo não 😬 

No que parece ser a resposta da API de módulos o preço é `23.47`, não é nem o original `23.57` nem o preço descontado que você pegou na request na Frenet, então acho que a request que você fez não é igual à que aconteceu no app, provavelmente tem alguma diferença nas dimensões dos produtos.

E no código a gente pega o preço descontado (quando há) sim, tá bem claro aqui: https://github.com/ecomplus/app-frenet/blob/master/routes/ecom/modules/calculate.js#L105-L106

> Tenta colar códigos em dentro de ```, facilita bem pra ler... https://guides.github.com/features/mastering-markdown/

**Comment by leomp12** [comment]
Ou talvez a diferença no seu teste seja o valor declarado...
Não quero dizer que que tá certo ou errado o app, só quero dizer que o teste que você fez aí não parece válido porque não perecem ser cálculos idênticos.
Além disso o `ShippingPrice` já é considerado sim (quando existe na resposta da Frenet), talvez o que acontece é que tá batendo uma outra regra de envio lá que você e o lojista não estão esperando, justamente por essa diferença com a simulação que você fez diretamente na Frente e o cálculo que é feito pelo app.

**Comment by matheusgnreis** [comment]
Rolou alguma mágica, esse teste ai eu fiz agora, já retornou 9,9 no mesmo produto. Eu já tinha visto que retornava com desconto, se tivesse, por isso achei muito estranho e abri. Mas parece que está ok agora
