### ISSUE TITLE
Incluir prazo de produção no cálculo do envio

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-frenet#15]
Algumas lojas que têm prazo de produção, esse prazo não é mostrado no cálculo e ai clientes reclamam que o prazo era x e não viram a informação do prazo.

**Comment by leomp12** [comment]
Não sei se entendi bem (porque não tá muito claro), mas não parece ser um issue daqui.
Você tá falando do prazo de produção configurado no produto? Isso nem passa pelo app da Frenet ou qualquer outro app de envio, talvez seja um enhancement do Storefront mas também não tenho certeza ainda, talvez se puder colocar um exemplo aqui ou explicar melhor...
