### ISSUE TITLE
Tracking frenet não funcionando corretamente

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-frenet#16]
ecomplus-integrations [Sun Aug 15 2021 23:34:50 GMT-0300 (Brasilia Standard Time)] 
>> Codigo de rastreio QG366209441BR salvo para o pedido 61102db733f3ce442f86ecee / #1077

O pedido foi entregue dia 18 e não foi alterado no pedido e nem apareceu no log. Alguns pedidos anteriores ocorreram o mesmo.

**Comment by leomp12** [comment]
Não tá atualizando nenhum ou é intermitente isso aí?

**Comment by leomp12** [comment]
Você achou algum log [desse](https://github.com/ecomplus/app-frenet/blob/master/lib/tracking-codes.js#L140) ou [desse](https://github.com/ecomplus/app-frenet/blob/master/lib/tracking-codes.js#L89) relacionado a esse código/pedido? Fez um teste direto na API da Frenet (análogo ao que é feito [aqui](https://github.com/ecomplus/app-frenet/blob/master/lib/frenet-api/fetch-tracking-code.js#L4-L14)) pra confirmar como tá lá?

**Comment by matheusgnreis** [comment]
> Não tá atualizando nenhum ou é intermitente isso aí?

No log, eu vi que tem uns com informação de entregue, mas para a loja do jonathan em si, parou tem algum tempo. Vi também que tem algumas lojas salvando o código de rastreio como null e outras salvando como link, não sei se isso poderia estar travando algo.

> Você achou algum log [desse](https://github.com/ecomplus/app-frenet/blob/master/lib/tracking-codes.js#L140) ou [desse](https://github.com/ecomplus/app-frenet/blob/master/lib/tracking-codes.js#L89) relacionado a esse código/pedido? Fez um teste direto na API da Frenet (análogo ao que é feito [aqui](https://github.com/ecomplus/app-frenet/blob/master/lib/frenet-api/fetch-tracking-code.js#L4-L14)) pra confirmar como tá lá?

Não tem nenhuma entrada de novo evento e nem de remove. Fiz o teste igual mostra e retornou um array, sendo que o primeiro era:

 {
      "SortDateTime": "0001-01-01T00:00:00",
      "EventDateTime": "18/08/2021 13:36",
      "EventLocation": "CAMPINAS-SP",
      "EventDescription": "Objeto entregue ao destinatário",
      "EventType": "9",
      "EventStatus": {},
      "CarrierEvent": {},
      "CarrierStatus": {}
    }

**Comment by matheusgnreis** [comment]
Último evento de entregue no log foi dia 26/07

ecomplus-integrations [Mon Jul 26 2021 23:13:15 GMT-0300 (Brasilia Standard Time)] 
NewEvent
{
  "message": "Novo Evento",
  "order_id": "60c9d5e6641ad82fcc29cb18",
  "storeId": 1077,
  "code": "OP166644508BR",
  "last_status": 1,
  "new_status": 9,
  "description": "Objeto entregue ao destinatÃ¡rio"
}

**Comment by talissonf** [comment]
Tem uma store aí que envia um link no lugar do código de rastreio. pode ser isso, mas nao tem travado nada nao, só os códigos que nao são válidos mesmo. Vou ver o que ta rolando. @leomp12 @matheusgnreis

**Comment by matheusgnreis** [comment]
Boa!

**Comment by talissonf** [comment]
@leomp12 @matheusgnreis  Fiz umas melhorias no app, to evitando salvar códigos de rastreio que não sejam válido, to removendo os códigos entregues com uma função que roda todos os dias. Antes eu tava removendo assim que ele mudava o status para entregue, mas as vezes eu removia o código do db e quando batia na ecom pra altera o status da order eu recebia o webhook novamente e o código voltava a ser salvo aumentando a fila.

Eu vi que @leomp12 colocou uma função la pra remover todos os códigos de rastreio que estavam no db a mais de dois meses mas sem criterio se ja havia sido entregue ou o que foi. Eu mantive la.

https://github.com/ecomplus/app-frenet/releases/tag/v0.2.30

**Comment by leomp12** [comment]
> Eu vi que @leomp12 colocou uma função la pra remover todos os códigos de rastreio que estavam no db a mais de dois meses mas sem criterio se ja havia sido entregue ou o que foi. Eu mantive la.

Acho que é suave manter porque não vai ter entrega que demore mais que 2 meses 😄 
Aí evita travar as filas com códigos velhos e que possam estar com algum status diferente talvez ou status nenhum..

> @leomp12 @matheusgnreis Fiz umas melhorias no app, to evitando salvar códigos de rastreio que não sejam válido, to removendo os códigos entregues com uma função que roda todos os dias.

Boa, valeu!

@matheusgnreis quer fazer um teste com os lojistas afetados ou fechamos o issue?

**Comment by matheusgnreis** [comment]
Em uma das lojas que não estavam funcionando, eu vi aqui e subiu ontem. Pode fechar o issue e vou começar a acompanhar
