### ISSUE TITLE
Falta de Tratativa quando Error volta igual a True

### ISSUE THREAD

**Issue by mateusvtoledo** [ecomplus/app-frenet#19]
Falta Tratativa quando uma das transportadoras a Frenet devolve com "Error": true e ainda existe outras opções de cotação junto a Frentet. Um exemplo:
 
 {
  "ShippingSevicesArray": [
    {
      "ServiceCode": "IBL_1",
      "ServiceDescription": "Transportadora",
      "Carrier": "Cardex Logistica",
      "CarrierCode": "IBL",
      "Msg": "Erro na consulta ao webservice da IbexLogistica.",
      "Error": true,
      "ResponseTime": "499.7243",
      "AllowBuyLabel": false
    },
    {
      "ServiceCode": "OWNE",
      "ServiceDescription": "Local",
      "Carrier": "Logistica Personalizada",
      "CarrierCode": "OWNE",
      "ShippingPrice": "60.00",
      "DeliveryTime": "7",
      "Error": false,
      "OriginalDeliveryTime": "7",
      "OriginalShippingPrice": "60.00",
      "ResponseTime": "18.83",
      "AllowBuyLabel": false
    },

Onde no front ele não exibe nada para o cliente, onde muito possívelmente e não está executando mais nada pois o status de erro dá frenet foi devolvido com  "Error": true.

**Comment by leomp12** [comment]
Rapaz verdade em, valeu pelo report 👍🏾
