### ISSUE TITLE
Acompanhamento de rastreio

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-frenet#5]
Referência: [Frenet API -> Tracking](https://frenetapi.docs.apiary.io/#reference/tracking)

Minha sugestão é criar um interval que executa uma função listando os códigos de rastreamento em aberto (não entregues) associados ao número da loja e pedido (salvar em BD).

Bate a API da Frenet e quando o status for entregue envia um POST para `/orders/_id/fulfillments` e remove a row do BD local.

**Comment by talissonf** [comment]
> Minha sugestão é criar um interval que executa uma função listando os códigos de rastreamento em aberto (não entregues) associados ao número da loja e pedido (salvar em BD).

listar de onde?

**Comment by leomp12** [comment]
Na quote aí eu sugeri _**salvar em BD**_, sqlite3 mesmo.
Mas você também pode listar via Store API com query pela forma de envio & status de entrega (`fulfillment_status`).

Easy-peasy :grinning:

**Comment by leomp12** [comment]
Ahhh mas a Frenet não retorna o tracking number, jóia demais :disappointed: 

Só dá listando via Store API então, além de bater forma de envio (Frenet) e o status de entrega, você teria que verificar se o tracking code tá preenchido na shipping line, sacou?
Teria que ser preenchido manualmente pelo lojista :name_badge:

**Comment by talissonf** [comment]
> Só dá listando via Store API então, além de bater forma de envio (Frenet) e o status de entrega, você teria que verificar se o tracking code tá preenchido na shipping line, sacou?

Eu to ligado, foi por isso que eu perguntei de onde listar...
Mas implemento da forma que você sugeriu.
