### ISSUE TITLE
Daemon services

### ISSUE THREAD

**Issue by talissonf** [ecomplus/app-frenet#6]
@leomp12 o applicativo não tá iniciando os serviços daemon, também não vi a env `DAEMON_SERVICES` setado no `node-frenet.services`, acho que pode ser isso.
Aproveitando, o serviço de atualização dos tracking_codes ta configurado pra iniciar depois de 5m que a ultima verificação foi feita. Pra alterar esse intervalo é só setar a env `TRACKING_SERVICE_INTERVAL` com o valor do intervalo em minutos ex; 5.

**Comment by leomp12** [comment]
Coloquei 30 mas registrou foi isto aqui em log:

```console
--> Update tracking codes is idle for 1800 minutes
```

**Comment by leomp12** [comment]
E tá dando repetidos erros 401 tentando registrar procedures (`POST /procedures.json`), joga em log e insiste em retentativas (bem frequentes por sinal) mesmo sem autorização.
Isto não deveria acontecer, pode dar uma olhada @talissonf ?
Vou remover o `DAEMON_SERVICES` por enquanto.

**Comment by talissonf** [comment]
> Coloquei 30 mas registrou foi isto aqui em log:
> 
> ```
> --> Update tracking codes is idle for 1800 minutes
> ```

Tá funcionando a atualização dos códigos de rastreio, como não tem nenhum salvo ele não executa a tarefa e entra em espera por 30m, minha divisão dos minutos no log que deve ta errada :man_facepalming:

**Comment by talissonf** [comment]
> E tá dando repetidos erros 401 tentando registrar procedures (`POST /procedures.json`), joga em log e insiste em retentativas (bem frequentes por sinal) mesmo sem autorização.
> Isto não deveria acontecer, pode dar uma olhada @talissonf ?
> Vou remover o `DAEMON_SERVICES` por enquanto.

É porque a versão antiga do frenet não utilizava procedures, nem pedia autorização em nenhum `scope` da api. Eu atualizei o app mas ficou algumas instalações antigas no db, ele ta tentando registrar o procedures pra essas instalações e como as instalações antigas não solicitava `post` em `/procedures.json` a api retorna esse 401 ele não marca a instalação como `setted_up` e ele tenta novamente registrar esse procedure e vira esse loop.

**Comment by leomp12** [comment]
Sim, tô ligado, existe um issue aberto sobre isso aqui https://github.com/ecomclub/ecomplus-app-sdk/issues/1

Mas pelo menos não deveria estar batendo todos os 401 em log, tá floodando o tempo todo até o usuário reinstalar o app, você tá POSTando os procedures só [aqui](https://github.com/ecomclub/app-frenet/blob/master/bin/local.js#L20)?

**Comment by talissonf** [comment]
> você tá POSTando os procedures só [aqui](https://github.com/ecomclub/app-frenet/blob/master/bin/local.js#L20)?

Sim, eu to usando a estrutura do boilerplate.

**Comment by leomp12** [comment]
Hmm, então isso pode ser um issue do boilerplate :disappointed: 
De qualquer forma temos que fixar aqui também pra poder rodar o serviço local, talvez se [editar](https://github.com/ecomclub/app-frenet/blob/master/bin/local.js#L23) para:

```js
} else if (!err.appAuthRemoved && (!err.response || err.response.status !== 401)) {
```

**Comment by talissonf** [comment]
Editei

**Comment by leomp12** [comment]
Reiniciei o serviço com o `DAEMON_SERVICES`
