### ISSUE TITLE
Inserir na configuração do aplicativo bairro, cidade e estado

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-frenet#8]
Além de deixar Rua, número e cep. Precisamos que o cliente consiga configurar Bairro, Cidade, Estado e complemento se houver. Para que dentro do pedido em remetente apareça corretamente todas as informações para que conseguimos gerar etiqueta correta, gerar declaração de conteúda correta e demais integrações que possam precisar dessa informação

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-frenet/commit/1cb17a3a94f402b9c3661153041bf8646a9e1718

**Comment by talissonf** [comment]
@matheusgnreis pronto.
